import * as React from '../node_modules/react/index.js';
export const createElement = React.createElement;
export const startTransition = React.startTransition;
export const useState = React.useState;
export const useEffect = React.useEffect;
export const useMemo = React.useMemo;
export const useCallback = React.useCallback;
export const useRef = React.useRef;
export const useContext = React.useContext;
export const useReducer = React.useReducer;
export const useLayoutEffect = React.useLayoutEffect;
export const Component = React.Component;
export const PureComponent = React.PureComponent;
export const Suspense = React.Suspense;
export const lazy = React.lazy;
export const forwardRef = React.forwardRef;
export const memo = React.memo;
export const Fragment = React.Fragment;
export const StrictMode = React.StrictMode;
export default React;
